create table demo_country (
  country_id      integer generated by default as identity primary key not null,
  country_name    varchar(255) not null,
  country_code    varchar(255) not null
);

INSERT INTO demo_country(country_id, country_name, country_code) VALUES (1,'Angola','AO');
INSERT INTO demo_country(country_id, country_name, country_code) VALUES (2,'Afghanistan','AF');
INSERT INTO demo_country(country_id, country_name, country_code) VALUES (3,'Albania','AL');
INSERT INTO demo_country(country_id, country_name, country_code) VALUES (4,'Algeria','DZ');
INSERT INTO demo_country(country_id, country_name, country_code) VALUES (5,'Andorra','AD');
INSERT INTO demo_country(country_id, country_name, country_code) VALUES (6,'Anguilla','AI');
INSERT INTO demo_country(country_id, country_name, country_code) VALUES (7,'Antigua and Barbuda','AG');
INSERT INTO demo_country(country_id, country_name, country_code) VALUES (8,'Argentina','AR');
INSERT INTO demo_country(country_id, country_name, country_code) VALUES (9,'Armenia','AM');
INSERT INTO demo_country(country_id, country_name, country_code) VALUES (10,'Australia','AU');
INSERT INTO demo_country(country_id, country_name, country_code) VALUES (11,'Austria','AT');
INSERT INTO demo_country(country_id, country_name, country_code) VALUES (12,'Azerbaijan','AZ');